[GL-4321] Documentation for embedded resources
gleannyc/documentation pull request #126
Opened 2023-04-26 23:13 UTC by dse0

I created a new section "Sharing Externally" and moved `Slack Integration` there as well. (and presumably will have public sharing here too.)

![screencapture-localhost-8005-docs-sharing-data-externally-iframe-embedding-2023-04-26-19_12_23](https://user-images.githubusercontent.com/26307902/234722021-4b7b071e-3280-4188-a12f-986e18f3cbd7.png)

2023-04-26 23:33 UTC, davidsonsarah commented
This looks great, so excited to have this published! 

Only change requested: can you please add in a section at the bottom that says "Coming Soon: Public Link Sharing" and include a link to the product roadmap?

2023-04-27 14:13 UTC, dse0 commented
> This looks great, so excited to have this published!
> 
> Only change requested: can you please add in a section at the bottom that says "Coming Soon: Public Link Sharing" and include a link to the product roadmap?

Sure, please remind me to remove it when we add a separate page for it.

2023-04-27 16:51 UTC, glean-calder requested changes
Looks great! Just a blocking request on including docs about models.

2023-04-27 16:51 UTC, glean-calder commented on docs/docs/sharing-data-externally/iframe-embedding.md
> +Embedded resources are also compatible with [Get Access Domains](../project-management/get-access-domains.md). If enabled, any user with an e-mail address from your organization's domain will be able
Nit: I think we always write `email` instead of `e-mail` in docs.

2023-04-27 16:53 UTC, glean-calder requested changes
Not sure where that comment about models went - rewrote it

2023-04-27 16:53 UTC, glean-calder commented on docs/docs/sharing-data-externally/iframe-embedding.md
> +To embed a Glean resource, add `viewMode=embed` to the URL parameters of your Saved View or Dashboard URL and set that URL to be the `src` of an `iframe` HTML tag.
We should also mention that you can embed models, and probably add an example of this too.

2023-04-27 16:54 UTC, glean-calder commented on docs/docs/sharing-data-externally/iframe-embedding.md
> +To embed a Glean resource, add `viewMode=embed` to the URL parameters of your Saved View or Dashboard URL and set that URL to be the `src` of an `iframe` HTML tag.
Side note - we don't seem to consistently use capitalization for Glean resources like `Saved View` and `Dashboard`. This does it the way I think we should - capitalizing them. But other docs don't.

@davidsonsarah, any thoughts on this before I write up a ticket to amend other docs that don't conform?

2023-04-27 17:22 UTC, glean-calder approved these changes
Awesome!

2023-04-27 17:22 UTC, glean-calder commented on docs/docs/sharing-data-externally/iframe-embedding.md
> +To embed a Glean resource, add `viewMode=embed` to the URL parameters of your Model, Saved View, or Dashboard URL and set that URL to be the `src` of an `iframe` HTML tag.
Nit: seems like we call these `Data Models` elsewhere in docs more than `Models`? Not blocking at all - we definitely need to take a pass at normalizing Glean vocabulary in our docs (cc @davidsonsarah for visibility)

2023-04-27 17:28 UTC, merged

2023-04-27 18:45 UTC, farkmarnum commented
@dse0 tiny nit — I believe the convention these days is to not capitalize the F in "iframe":

- [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)
- [W3C](https://www.w3.org/TR/2011/WD-html5-20110525/the-iframe-element.html#the-iframe-element)